project:
  type: website
  output-dir: _site

pagetitle: "PhD Thesis Defense"
title: "Sustainable Transportation,<br>Sustainable Research:<br><span style='font-size: 0.7em; color: #2C8475; display: inline-block; line-height: 1.5;'>Consumer Adoption and Grid Peak-Shaving<br>of Battery Electric Vehicle Smart Charging,<br>Inspiring the `surveydown` Survey Platform</span>"
author: "<br>**Pingfan Hu**<br>George Washington University"

format:
  touhou-revealjs:
    smaller: false
    css: styles/slides.css
    bibliography: bibliography.bib
    csl: styles/apa.csl
    slide-number: true
    embed-resources: false
    auto-stretch: false
    preview-links: auto
    logo: figs/logo.png
    footer: "<a href='http://pingfanhu.com'>Pingfan Hu</a> - PhD Thesis Defense"
    link-external-newwindow: true
    link-external-icon: false
    center-title-slide: true
    code-block-height: 650px
    title-slide-attributes:
      class: custom-title-slide
      style: "text-align:left; background-image: url(figs/logo.png);"

execute: 
  warning: false
  echo: false
